### ISSUE TITLE
image repository not up2date

### ISSUE THREAD

**Issue by HaveFun83** [kubermatic/kubelet#27]
Hi 

the quay.io/kubermatic/kubelet container image repository is missing the actual kubernetes releases.

```
❯ docker pull quay.io/kubermatic/kubelet:v1.20.8
Error response from daemon: manifest for quay.io/kubermatic/kubelet:v1.20.8 not found: manifest unknown: manifest unknown
❯ docker pull quay.io/kubermatic/kubelet:v1.21.2
Error response from daemon: manifest for quay.io/kubermatic/kubelet:v1.21.2 not found: manifest unknown: manifest unknown
```

**Comment by rwin-novo** [comment]
We've also just found this issue. I assume the image has been built, but it's not tagged, maybe as a side-effect of https://github.com/kubermatic/kubelet/pull/25 ?

**Comment by xrstf** [comment]
Thanks for reporting, I'm looking into it.

**Comment by xrstf** [comment]
Our CI system seems to have skipped the latest round of tags for some reason(TM). I have re-tagged the same revisions to trigger the builds, the images should appear within the hour on quay.

Sorry for the interruption.

**Comment by xrstf** [comment]
Images have been pushed. We'll keep an eye on this to prevent it from happening again.

**Comment by HaveFun83** [comment]
@xrstf thanks a lot for the quick response.
